Repository TheBenchwarmer21/TheBookaholics, pull requests merged in 2023-11, with the labels that each got.

#29 Configured auto generated release notes
  .github/release.yml
Labels: minor

#31 VERY Basic my review page functionality implemented
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/views/pages/myreviews.ejs
  All_Project_Code_And_Components/views/partials/footer.ejs
  All_Project_Code_And_Components/views/partials/header.ejs
Labels: minor

#35 Fixed a typo causing redirect to login even when successfully logged in.
  All_Project_Code_And_Components/index.js
Labels: minor

#39 Fixed error that wont let user register, also accounted for all known…
  All_Project_Code_And_Components/index.js
Labels: minor

#46 Basic myreview grid card functionality, still lots to do
  All_Project_Code_And_Components/views/pages/myreviews.ejs
  All_Project_Code_And_Components/views/partials/header.ejs
Labels: minor

#52 Completed code portion of lab11, read desc for more details.
  All_Project_Code_And_Components/docker-compose.yaml
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/package.json
  All_Project_Code_And_Components/test/server.spec.js
Labels: major

#55 Search Results Page Working
  All_Project_Code_And_Components/index.js
Labels: major

#59 Register
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
Labels: major

#60 completed login page
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
Labels: major

#61 added logout page
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
Labels: minor

#69 Yusef's code for /Login and /Register
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/test/server.spec.js
Labels: minor

#72 Added Lab11 PDF to milestone submissions folder
  Milestone_Submissions/Lab 11.pdf
Labels: minor

#79 Closes #77, Closes #76;
  All_Project_Code_And_Components/views/pages/searchbarresult.ejs
Labels: minor

#80 Closes #78
  All_Project_Code_And_Components/resources/img/BetterLibrary.jpeg
  All_Project_Code_And_Components/resources/img/WoodBackround.avif
  All_Project_Code_And_Components/views/pages/home.ejs
  All_Project_Code_And_Components/views/pages/searchbarresult.ejs
Labels: minor

#81 Search input
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/views/pages/home.ejs
  All_Project_Code_And_Components/views/pages/searchbarresult.ejs
Labels: major

#82 Add Books Functionality Working
  All_Project_Code_And_Components/docker-compose.yaml
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/views/pages/home.ejs
  All_Project_Code_And_Components/views/pages/searchbarresult.ejs
  All_Project_Code_And_Components/views/partials/message.ejs
Labels: major

#87 Closes #86, Closes #85
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/views/pages/searchbarresult.ejs
Labels: major

#88 Closes #84, Closes #83
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/views/pages/home.ejs
  All_Project_Code_And_Components/views/pages/searchbarresult.ejs
Labels: minor

#91 Working card grid, working modals. Still need to add edit review feature
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/views/pages/myreviews.ejs
Labels: major

#92 All functionality present, just need to implement pages for when there are a large number of reviews
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/views/pages/myreviews.ejs
Labels: major

#93 Myreviews functionality fully implemented
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/views/pages/myreviews.ejs
Labels: major

#97 welcome adjustment
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
Labels: enhancement

#100 Closes #98
  All_Project_Code_And_Components/index.js
Labels: enhancement

#102 closes #101
  All_Project_Code_And_Components/resources/img/book.jpg
  All_Project_Code_And_Components/resources/img/nice.jpg
  All_Project_Code_And_Components/views/pages/Welcome.ejs
Labels: enhancement

#104 closes #103
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
Labels: enhancement, minor

#106 Closes #105
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
Labels: duplicate, enhancement

#110 closes #109
  All_Project_Code_And_Components/views/pages/Welcome.ejs
Labels: enhancement

#112 closes #111
  All_Project_Code_And_Components/views/pages/Welcome.ejs
  All_Project_Code_And_Components/views/pages/myreviews.ejs
Labels: enhancement

#114 closes #113
  All_Project_Code_And_Components/views/pages/home.ejs
  All_Project_Code_And_Components/views/pages/myreviews.ejs
  All_Project_Code_And_Components/views/pages/reviews.ejs
Labels: enhancement, minor

#116 closes #115
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
  All_Project_Code_And_Components/views/pages/Welcome.ejs
  All_Project_Code_And_Components/views/pages/home.ejs
  All_Project_Code_And_Components/views/pages/myreviews.ejs
Labels: enhancement, minor

#118 closes 117
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
Labels: enhancement

#121 closes #119
  README.md
Labels: documentation

#123 closes #62
  All_Project_Code_And_Components/index.js
Labels: documentation

#125 closes #5
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
  All_Project_Code_And_Components/views/partials/header.ejs
Labels: documentation

#129 Removesearch
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
Labels: enhancement

#131 Closes #130
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
  All_Project_Code_And_Components/views/pages/myreviews.ejs
Labels: enhancement

#132 Closes #95
  All_Project_Code_And_Components/.DS_Store
  All_Project_Code_And_Components/index.js
  All_Project_Code_And_Components/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
  All_Project_Code_And_Components/views/pages/searchbarresult.ejs
Labels: major

#134 Fixed error in add_review route causing duplicate book entries in books table
  All_Project_Code_And_Components/index.js
Labels: minor

#135 Closes #133 ~ yellow table
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
Labels: enhancement

#136 Added week 2 TA slide deck and weekly release notes to Milestone_Submissions
  All_Project_Code_And_Components/views/pages/myreviews.ejs
  Milestone_Submissions/Release Notes/wk1 release notes.png
  Milestone_Submissions/Release Notes/wk2 release notes.png
  Milestone_Submissions/Release Notes/wk3 release notes.png
  Milestone_Submissions/Weekly TA slides/TA Weekly Meeting #2 .pdf
Labels: exclude from release

#144 closes #143 added cards
  All_Project_Code_And_Components/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
  All_Project_Code_And_Components/views/pages/Mybooks.ejs
Labels: enhancement, minor
